$ANSIBLE_VAULT;1.1;AES256
38346534313839396364643763613033623131626432363533323163346231353938636565663532
3831356639326330626137363162626261373733646362390a616430313230326361646434383939
36626530343735643233653063316365343936303863353737383230643334346232306231393533
3266303862613261360a653938313365363139353636643061663766333161326563646530323832
61393138363030343932343930313732653237643132323432636562643238666564653535376431
30356561336238633434646562666531663266373835613833363538633937303366306132343866
38333732306364643932363362363032646137666366333039313738366135333431353362646532
35306638633336316265
